### ISSUE TITLE
Excellent size reduction in latest version.

### ISSUE THREAD

**Issue by mgeisler** [axelf4/unicode-linebreak#5]
Hi Alex,

This is not really an issue, I just wanted to say thank you for https://github.com/axelf4/unicode-linebreak/commit/4f916faa1fdaf541390bb3e686f0b20042a04ca6, that change is awesome!

I can confirm that this change lowers the binary size of unicode-linebreak in an actual program using Textwrap from 102 KB to 53 KB.

Before, with unicode-linebreak version 0.1.2, compiling Textwrap with different feature flags gave these sizes:

| Configuration                            |  Binary Size |    Delta |
| :---                                     |         ---: |     ---: |
| quick-and-dirty implementation           |       289 KB |     — KB |
| textwrap without default features        |       305 KB |    16 KB |
| textwrap with smawk                      |       317 KB |    28 KB |
| textwrap with unicode-width              |       309 KB |    20 KB |
| textwrap with unicode-linebreak          |       391 KB |   102 KB |

Now, with unicode-linebreak 0.1.3, I measure these sizes:

| Configuration                            |  Binary Size |    Delta |
| :---                                     |         ---: |     ---: |
| quick-and-dirty implementation           |       289 KB |     — KB |
| textwrap without default features        |       305 KB |    16 KB |
| textwrap with smawk                      |       317 KB |    28 KB |
| textwrap with unicode-width              |       309 KB |    20 KB |
| textwrap with unicode-linebreak          |       342 KB |    53 KB |

This is from running `cargo run --example make-table` in the [binary-sizes demo in Textwrap](https://github.com/mgeisler/textwrap/tree/master/examples/binary-sizes).

**Comment by axelf4** [comment]
:+1: Actually, seeing that table was what motivated me to do something about it.

**Comment by mgeisler** [comment]
Cool, I'm glad it was useful!
