### ISSUE TITLE
Pre-generate `tables.rs` instead of doing it in `build.rs`?

### ISSUE THREAD

**Issue by NobodyXu** [axelf4/unicode-linebreak#7]
Generating `tables.rs` requires `unicode-linebreak` to pull in `regex` and `hashbrown` as build-dependencies, plus running the generation at compile-time, which makes compilation a lot slower.

Since `LineBreak.txt` doesn't change that often, generating it manually won't make it much harder to maintain,

I can submit a PR to convert the `build.rs` to a separate crate that is never published and can be run locally to consume the `LineBreak.txt` and generate `src/tables.rs`, does it sound good to you?

If you insist on keeping the `build.rs`, it might be a good idea to switch to regex-lite https://github.com/rust-lang/regex/issues/961

**Comment by axelf4** [comment]
> I can submit a PR to convert the `build.rs` to a separate crate that is never published and can be run locally to consume the `LineBreak.txt` and generate `src/tables.rs`, does it sound good to you?

Sure!, as long as it does not entail checking in the generated `src/tables.rs` into source control. (I think that should be avoidable by adding it to both `.gitignore` and the `include` field in `Cargo.toml`?)

**Comment by NobodyXu** [comment]
> Sure!, as long as it does not entail checking in the generated src/tables.rs into source control. (I think that should be avoidable by adding it to both .gitignore and the include field in Cargo.toml?)

Yes, that's doable.
I will submit a PR for this.

**Comment by BurntSushi** [comment]
Can you say why you don't want to check the generated tables into source code? I do it for all my crates, like `regex-syntax` and `bstr`. It's the best of both worlds: you don't need to pass on your `build-dependencies` and you don't need any bespoke build instructions and you don't need to do things like `cargo publish --allow-dirty`. It's just `cargo build` and everything works.
